//
// This file is auto-generated by CMake.
//

#pragma once

#define PL_GIT_COMMIT_HASH_SHORT 3d19a12a4343
#define PL_GIT_COMMIT_HASH_LONG 3d19a12a43431c504e5e118da009bd0296b3d18f
#define PL_GIT_BRANCH_NAME "main"

